name: run_eslint
on: [push]
jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: npm install
        run: 
          make install
      - name: Run Linter
        run: 
          make lint
      - name: Run test
        run: 
          make jest
      - name: Test & publish code coverage
      # Publish code coverage on Code Climate
      # https://github.com/paambaati/codeclimate-action
        uses: paambaati/codeclimate-action@v3
      # Add Code Climate secret key
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.TEST_COVERAGE }}
        with:
          coverageCommand: make cover
          debug: true